drop table AUTHORITIES;
drop table USERS;

create table USERS(
    USERNAME varchar(128) PRIMARY KEY,
    PASSWORD varchar(128) NOT NULL,
    ENABLED char(1) CHECK (ENABLED IN ('Y','N') ) NOT NULL
);

CREATE TABLE AUTHORITIES (
    USERNAME VARCHAR(128) NOT NULL,
    AUTHORITY VARCHAR(128) NOT NULL
);

ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);

INSERT INTO USERS (USERNAME,PASSWORD,ENABLED) VALUES ('test', '$2y$12$nK9BdjDApW3YazJpw9P6u.iRZbaTsURABG9PkWKHFepsvZ4gLC.u2', 'Y');
INSERT INTO AUTHORITIES (USERNAME,AUTHORITY) VALUES ('test', 'user');

SELECT * FROM USERS INNER JOIN AUTHORITIES ON AUTHORITIES.USERNAME = USERS.USERNAME;
